"""
compute_annotation_agreement.py
---------------------------------
Reads two completed annotation Excel sheets and computes:
  - Inter-annotator agreement (Cohen's kappa)
  - Precision, Recall, F1 of automated vocabulary extractor
    vs human consensus

Usage:
    python compute_annotation_agreement.py

Expects:
    Results/annotation_sheet_A.xlsx   (completed by Annotator A)
    Results/annotation_sheet_B.xlsx   (completed by Annotator B)
    Results/annotation_samples.csv    (generated by generate_annotation_samples.py)
    safe_gem/claim_extractor.py       (automated extractor)

Run from safe_gem folder.
"""

import os, sys
import pandas as pd
import numpy as np
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

RESULTS_DIR = r"C:\Users\Valued User\Desktop\Office PhD\agentic_egs\agentic_egs\agentic_egs\Results"

SHEET_A = os.path.join(RESULTS_DIR, "annotation_sheet_A.xlsx")
SHEET_B = os.path.join(RESULTS_DIR, "annotation_sheet_B.xlsx")
SAMPLES = os.path.join(RESULTS_DIR, "annotation_samples.csv")

VALID_VERDICTS = {"SUPPORTED", "CONTRADICTED", "UNAVAILABLE"}


# ── 1. Load completed annotation sheets ─────────────────────────────────────

def load_sheet(path, annotator_label):
    """Load annotation sheet — reads from the Annotations tab."""
    df = pd.read_excel(path, sheet_name="Annotations", header=1)
    # Columns: Annot ID | Strategy | GT|Pred|Conf | Evidence | Explanation |
    #          Claim # | Claim Phrase | Feature Group | Verdict | Notes
    df.columns = ["annot_id","strategy","gt_pred_conf","evidence",
                  "explanation","claim_num","claim_phrase",
                  "feature_group","verdict","notes"]

    # Drop empty claim rows
    df = df[df["claim_phrase"].notna() & (df["claim_phrase"] != "")]
    df = df[df["claim_phrase"].astype(str).str.upper() != "N/A"]
    df["verdict"] = df["verdict"].astype(str).str.upper().str.strip()
    df["verdict"] = df["verdict"].apply(
        lambda v: v if v in VALID_VERDICTS else "UNAVAILABLE"
    )
    df["annotator"] = annotator_label

    # Forward fill annot_id (merged cells appear as NaN after row 1)
    df["annot_id"] = df["annot_id"].ffill()
    df["strategy"] = df["strategy"].ffill()

    print(f"  {annotator_label}: {len(df)} claims from "
          f"{df['annot_id'].nunique()} explanations")
    return df


# ── 2. Align claims between annotators for kappa ─────────────────────────────

def align_annotations(df_a, df_b):
    """
    For each explanation, match claims between annotators by closest
    phrase similarity (simple token overlap).
    Returns pairs of (verdict_A, verdict_B) for kappa calculation.
    """
    from difflib import SequenceMatcher

    pairs = []
    for annot_id in df_a["annot_id"].unique():
        claims_a = df_a[df_a["annot_id"]==annot_id]["claim_phrase"].tolist()
        verdicts_a = df_a[df_a["annot_id"]==annot_id]["verdict"].tolist()
        claims_b = df_b[df_b["annot_id"]==annot_id]["claim_phrase"].tolist() \
                   if annot_id in df_b["annot_id"].values else []
        verdicts_b = df_b[df_b["annot_id"]==annot_id]["verdict"].tolist()

        # Match each A claim to the closest B claim
        used_b = set()
        for ca, va in zip(claims_a, verdicts_a):
            best_j, best_sim = -1, 0
            for j, cb in enumerate(claims_b):
                if j in used_b:
                    continue
                sim = SequenceMatcher(None,
                    ca.lower().split(), cb.lower().split()).ratio()
                if sim > best_sim:
                    best_sim, best_j = sim, j
            if best_j >= 0 and best_sim > 0.4:
                pairs.append((va, verdicts_b[best_j]))
                used_b.add(best_j)

    return pairs


def cohen_kappa(pairs):
    """Compute Cohen's kappa from (rater_A, rater_B) verdict pairs."""
    from sklearn.metrics import cohen_kappa_score
    if not pairs:
        return 0.0, 0
    ra, rb = zip(*pairs)
    kappa  = cohen_kappa_score(ra, rb, labels=list(VALID_VERDICTS))
    return round(kappa, 3), len(pairs)


# ── 3. Compare automaton vs consensus ─────────────────────────────────────────

def compare_auto_vs_human(samples_csv, df_a, df_b):
    """
    For each explanation in annotation_samples.csv, run the automated
    claim extractor and compare to human consensus annotation.
    """
    from safe_gem.claim_extractor import ClaimExtractor
    from safe_gem.symbolic_converter import SymbolicConverter

    samples_df = pd.read_csv(samples_csv)
    extractor  = ClaimExtractor()
    conv       = SymbolicConverter()

    TP = FP = FN = 0
    verdict_pairs = []   # for per-verdict precision/recall

    for _, row in samples_df.iterrows():
        annot_id = row["annot_id"]
        expl     = str(row["explanation_text"])

        # Human consensus: claim phrase present in BOTH annotators
        ha = set(df_a[df_a["annot_id"]==annot_id]["claim_phrase"]
                 .str.lower().tolist())
        hb = set(df_b[df_b["annot_id"]==annot_id]["claim_phrase"]
                 .str.lower().tolist())
        # Consensus = phrases found by at least one annotator
        # (union; use intersection for stricter consensus)
        human_claims = ha | hb

        # Automated extraction
        auto_claims  = set(c.raw_phrase.lower()
                           for c in extractor.extract_claims(expl))

        # Token-level matching
        for hc in human_claims:
            matched = any(_token_overlap(hc, ac) > 0.5
                          for ac in auto_claims)
            if matched:
                TP += 1
            else:
                FN += 1

        for ac in auto_claims:
            matched = any(_token_overlap(ac, hc) > 0.5
                          for hc in human_claims)
            if not matched:
                FP += 1

    precision = TP / (TP + FP) if (TP + FP) > 0 else 0
    recall    = TP / (TP + FN) if (TP + FN) > 0 else 0
    f1        = (2 * precision * recall / (precision + recall)
                 if (precision + recall) > 0 else 0)

    return {
        "TP": TP, "FP": FP, "FN": FN,
        "precision": round(precision, 3),
        "recall":    round(recall, 3),
        "f1":        round(f1, 3),
    }


def _token_overlap(a: str, b: str) -> float:
    from difflib import SequenceMatcher
    return SequenceMatcher(None, a.lower().split(), b.lower().split()).ratio()


# ── 4. Save results ───────────────────────────────────────────────────────────

def save_results(kappa, n_pairs, auto_metrics, df_a, df_b, out_dir):
    """Save agreement results to Excel."""
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment

    wb  = Workbook()
    ws  = wb.active
    ws.title = "Agreement Results"

    bold = Font(bold=True, name="Arial", size=11)
    hdr  = PatternFill("solid", start_color="1F4E79")
    hf   = Font(bold=True, color="FFFFFF", name="Arial")

    ws["A1"] = "SAFE-GEM Annotation Agreement Report"
    ws["A1"].font = Font(bold=True, name="Arial", size=14)
    ws.merge_cells("A1:D1")

    rows = [
        ["Metric",                         "Value",  "Threshold",  "Pass?"],
        ["Inter-annotator kappa (κ)",       kappa,    "≥ 0.70",
         "YES" if kappa >= 0.70 else "NO — needs re-annotation"],
        ["Matched pairs for kappa",        n_pairs,  "≥ 20",
         "YES" if n_pairs >= 20 else "LOW"],
        ["Auto extractor Precision",        auto_metrics["precision"], "≥ 0.70", ""],
        ["Auto extractor Recall",           auto_metrics["recall"],    "≥ 0.65", ""],
        ["Auto extractor F1",               auto_metrics["f1"],        "≥ 0.70",
         "YES" if auto_metrics["f1"] >= 0.70 else "BELOW TARGET"],
        ["True Positives",                  auto_metrics["TP"],        "",       ""],
        ["False Positives",                 auto_metrics["FP"],        "",       ""],
        ["False Negatives",                 auto_metrics["FN"],        "",       ""],
        ["Total A claims",                  len(df_a),                 "",       ""],
        ["Total B claims",                  len(df_b),                 "",       ""],
    ]

    ws.append([])  # blank row
    for i, row in enumerate(rows):
        ws.append(row)
        if i == 0:
            for col in range(1, 5):
                c = ws.cell(ws.max_row, col)
                c.font = hf
                c.fill = hdr

    ws.column_dimensions["A"].width = 35
    ws.column_dimensions["B"].width = 15
    ws.column_dimensions["C"].width = 15
    ws.column_dimensions["D"].width = 30

    # Per-explanation sheet
    ws2 = wb.create_sheet("Per-explanation")
    ws2.append(["Annot ID","Strategy","A claims","B claims",
                "Auto claims","A∩B","Auto∩(A∪B)"])

    out_path = os.path.join(out_dir, "annotation_agreement_results.xlsx")
    wb.save(out_path)
    print(f"\nResults saved: {out_path}")


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("Loading completed annotation sheets...")

    if not os.path.exists(SHEET_A) or not os.path.exists(SHEET_B):
        print("ERROR: annotation sheets not found.")
        print(f"  Expected: {SHEET_A}")
        print(f"  Expected: {SHEET_B}")
        print("Complete the annotation study first, then re-run.")
        exit(1)

    df_a = load_sheet(SHEET_A, "A")
    df_b = load_sheet(SHEET_B, "B")

    print("\nComputing inter-annotator agreement...")
    pairs = align_annotations(df_a, df_b)
    kappa, n_pairs = cohen_kappa(pairs)
    print(f"  Cohen's kappa: {kappa} ({n_pairs} matched pairs)")
    if kappa >= 0.70:
        print("  ✓ Substantial agreement — annotation is reliable")
    elif kappa >= 0.60:
        print("  ~ Moderate agreement — acceptable but borderline")
    else:
        print("  ✗ Low agreement — review annotation guidelines and re-annotate")

    print("\nComputing automated extractor precision/recall...")
    try:
        auto_metrics = compare_auto_vs_human(SAMPLES, df_a, df_b)
        print(f"  Precision: {auto_metrics['precision']}")
        print(f"  Recall:    {auto_metrics['recall']}")
        print(f"  F1:        {auto_metrics['f1']}")
        print(f"  TP={auto_metrics['TP']}  FP={auto_metrics['FP']}  "
              f"FN={auto_metrics['FN']}")
    except Exception as e:
        print(f"  Auto comparison failed: {e}")
        auto_metrics = {"TP":0,"FP":0,"FN":0,"precision":0,"recall":0,"f1":0}

    save_results(kappa, n_pairs, auto_metrics, df_a, df_b, RESULTS_DIR)

    print("\n=== Summary for paper (MC2 response) ===")
    print(f"  Annotator agreement: κ = {kappa}")
    print(f"  Automated extractor: P={auto_metrics['precision']} "
          f"R={auto_metrics['recall']} F1={auto_metrics['f1']}")
    print(f"  These values go into revised Section 6.4")
